name: Continuous Integration

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: strongpassword
          POSTGRES_DB: forumapi_test

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: npm install migrate and test
      run: |
        mv .env.test .env
        npm install
        npm run migrate up
        npm run test
      env:
        CI: true
