name: Continuous Integration

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: strongpassword
          POSTGRES_DB: forumapi_test
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate up
        npm run test
      env:
        CI: true
        HOST: localhost
        PORT: 5000
        PGHOST: database
        PGUSER: postgres
        PGDATABASE: forumapi_test
        PGPASSWORD: strongpassword
        PGPORT: 5432
        PGHOST_TEST: database
        PGUSER_TEST: postgres
        PGDATABASE_TEST: forumapi_test
        PGPASSWORD_TEST: strongpassword
        PGPORT_TEST: 5432
        ACCESS_TOKEN_KEY: strongaccesstokenkey
        REFRESH_TOKEN_KEY: storngrefreshtokenkey
        ACCCESS_TOKEN_AGE: 3000
